### ISSUE TITLE
2022-05-29 - dependabot の auto-merge 用に、PAT(Personal Access Token) 無しの GITHUB_TOKEN だけで GitHub Actions の CI 完了待ち出来るようなのを作ってみた

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#163]
## TL;DR

```yaml
name: Auto merge dependabot PRs if passed other jobs
on: pull_request

permissions:
  contents: write
  pull-requests: write
  # checks: read # For private repositories
  # actions: read # For private repositories

jobs:
  auto-merge-dependabot-prs:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Wait other jobs are passed or failed
        if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        uses: kachick/wait-other-jobs@v1-beta
        timeout-minutes: 30
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto approve and merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

[自分はちょっと変えてこうしてる](https://github.com/kachick/rspec-matchers-power_assert_matchers/blob/650a0ef0c290d42cd0a70ef7c011de2c3777c966/.github/workflows/auto-merge-dependabot-prs.yml)

`--squash` は自分の好み。普通は？ `--merge` だと思う。

## 何についてか / About

ref: 

* [kachick/wait-other-jobs](https://github.com/kachick/wait-other-jobs)
* https://github.com/dependabot/dependabot-core/issues/1973

## 経緯 / History

dependabot の auto merge 機能が GitHub の公式提供から外されて、最近でも python のライブラリに悪意あるコード埋め込まれたとかあるししょうが無いよなぁとは思うものの、まーやっぱり無いと現実問題厳しい感じ。
その後幾つか 3rd party の auto merge が乱立してたと思うんだけど、なるべく Official な機能だけで実現したかった。
で、数ヶ月前にうんうん 言いながら唸って 自動で approve した後に `@dependabot merge` を自動でコメントさせるような GitHub Actions を作った。approve させるようにしたのはそのリポジトリの merge 必須要件に入っていたため。そしてこのコマンドを受け付けた dependabot さんは賢い事に全部の job が通った時にだけ merge してくれるということでやれやれと思ってたんだけど、ネックが幾つか。まず仕様として bot からのコマンドを受け付けないらしく、そのリポジトリに権限を持ったアカウントの PAT(Personal Access Token) を用意して使わないといけないというキモさ。次にそのトークンを読むために pull_request_target  を trigger にしないといけなかった。辛い。
ここ最近 permission というのを設定できるようになったみたいで、当時と違い今は pull_request_target を捨てれるだろうけど、 bot からのコマンドを受け付けないという事情は変わってない様子。[久しぶりに調べたら同じアプローチを取ってる GitHub Actions も marketplace で見つけた](https://github.com/marketplace/actions/dependabot-auto-merge)んだけど、やはり PAT が必要な様子。
PAT はアカウントに紐づく為、リポジトリ単位とかで権限のスコープを絞ることが出来ない。[これの拡張は GitHub も検討しているみたいだけどまだ実現してない。](https://github.community/t/limiting-scope-of-a-pat-to-a-single-repository/3129/4)

そもそも GitHub はこの需要をどう考えているんじゃいと公式ドキュメントを追ってみると、今は流石に声が多すぎるからか[オフィシャルにこうするといいよというのを書いてくれてた。](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions) で、はっきりと  `@dependabot merge` のようなコマンド発行自動化は推奨しないと言っている issue も見つけたんだけどどこだったか分かんなくなった。(この話題の issue とか記事多すぎ)
なるほど、このドキュメントだと https://github.com/dependabot/fetch-metadata を使ってバージョンの上がり方を引っ張ってきている。で、 gh コマンドで approve や merge をしている。
それは良いんだけど、どうやらCI待ちをさせていない・・・ repository のマージ要件にCI待ちの設定を入れてしまえば実質待たせることにはなるだろうけど、 dependabot の為にリポジトリ設定を変えたくはない。

というところで、どの方法を選択しようがあちらを選べばこちらがたたずな感じだったので、不慣れながら自作してみた。
最初は dependabot auto-merge だけに絞ったアクションを作ってたんだけど、色んな言語向け version update の正規表現を自前で正確に書くみたいなのは筋が悪い感じだし、merge 部分は gh コマンドに投げてるしで大半はCI(他の job)待ちのコードになってしまったので、単独機能としてリリースして GitHub Official の steps に挟むこむようにした。
action、workflow、job、step、run の定義すらあんま良くわかってないんだけど、今のところちゃんと動いてそうに見える。

自分の要件は満たせてしまったのでこれ以上あんま深追いしたくないんだけど、気になっているのは以下

* dependabot の config でCI通ったら？ラベルをつけさせて、そのラベルをみてマージするというワーカー的な機能を走らせて置くという[もの](https://github.com/apps/mergery)。PAT や 3rd party アプリへの oauth 不要ならこれもありな気はするけど、特定の dependency に関してはラベルを付けさせないとかまでは dependabot config に無さそうなので劇的に便利とは行かなそうな気が・・・。と思ってたけど https://github.com/marketplace/actions/merge-pull-requests-automerge-action とか PAT 不要そうだし、dependabot 以外で automerge ラベルは無視みたいなとこまで条件書けばこれで良いのかもなー
* 自分は check-runs を前段の api で run_id 拾った上で叩くみたいにしているんだけど、 https://mixi-developers.mixi.co.jp/github-action-all-check-ci-cad4d862f137#3f63 で書かれていた check-suites とやらがなんでどういう違いがあるのかとかがあんまよくわかってない・・・
* https://github.com/lewagon/wait-on-check-action も check-runs を叩いているらしいんだけど、name を渡しているみたいなので前段の run_id を引っこ抜く処理とかが無いから設定が増えているのでは・・・と想像しているんだけど追えてない

書いていた時の雑感

* v3(REST) だけで v4(GraphQL) の api 用意されてない機能が結構ある。
* REST api に対する TypeScript の型定義がうまい感じで気持ちよく使えた。
* ページング機能を用意してくれるのはとても嬉しいけど対応させるの面倒だった。というかまず発生しないだろと思ってサボってる。その内実装するかも。
* 流石に色んなタスクがあるからか実現してない話は一杯あるみたいだけど、 GitHub は色んな要望をちゃんと理解はしてくれて質疑応答をしてくれるので https://github.community/ とかちゃんと追った方が良さそう。全体的に良心的だよなーとは思う。
* ローカルじゃないところの ENV とかに渡ってくるものに対するコード書くの大変だし意外なところでハマって時間食う。ログは最後の仕上げに出そうと思ってたけど、開発途中でも合ったほうが諸々捗る。
* Exponential Backoff ぐらいサラッとかけるやろ！とか Promise/await/async 周りも雰囲気で行けるやろ！と思ってたけど一回目に書いたコードは大体バグってた。
* Ruby でもそうだけど1行に記号を使った計算や条件が詰め込まれているようなコードだと、優先順位的に不要でも `()` つけまくりたくなるのに eslint-airbnb ? prettier? さんが消しちゃうのでカスタマイズも探さず唯々諾々と消されてたけど納得してない。
* ECMA Script の Destructuring assignment わかってるつもりだったけどネストした時にどこまで柔軟に書けるのかあんま良くわかってなかった。
* かなり時間費やしたところで自分が取ってたIDは run_id ではなく、これをダイレクトに取る方法がない事がわかりちょっと泣きそうになったけど https://github.com/actions/starter-workflows/issues/292#issuecomment-922372823 に救われた。
* GitHub marketplace で公開するの簡単。というか action のリポジトリを作るとそうしろと勧めてくる。
* これまでに大勢挑んでる感がある話なので、どっかに全く同じか上位互換 action がリリースされてて完全に車輪の再発明だった可能性も捨てきれないけど、そしたら勉強になったからよしと思うことにする(嘘、多分凹む)。
* 🐔 なので v1-beta タグのまま使ってるけど、どっかで v1 にしないとなぁと思っては居る。
* dependabot/fetch-metadata の出力を取り回す様な action も書こうかと思ったけど、 action だけで types とかの npm 提供無いしまーいっかー？と思っている。
* dependabot/fetch-metadata の出力を、その後の step 全部の if に同じ取り回しコード書いて skip に使ってるの流石にダサいとは思うけど腰が上がらない。
