### ISSUE TITLE
2024-10-25 - GitHub Action 内の外部コマンドが死んだときにはそれを走らせた pwsh も同じコードで死んでほしい

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#312]
## TL; DR

https://github.com/kachick/dotfiles/blob/ba29c4b685b4e8923c6133737936ddc432e3ba55/.github/workflows/windows.yml#L34-L42

```yaml
defaults:
  run:
    shell: |
      pwsh -command "$PSNativeCommandUseErrorActionPreference = $true; $ErrorActionPreference = 'stop'; . '{0}'"
```

## ごちゃごちゃ

という問題が昔からあったんだけれど、これを解決できる PSNativeCommandUseErrorActionPreference とやらが後方互換性のためにデフォルトOffで出荷された＆GitHub Actionでも影響でかすぎるだろうとOffのままなので、無理やり有効化してやればいい。尚若干元のpwshのコマンドラインとは異なるんだけれど、このあたりチューニングしようとすると多分 pwsh 以外の pwsh-err みたいなプリセットを runner 側に用意してくれないと難しい気はしている

というのをこないだ調べて github docs にPRとかだしたほうが良いんだろうなと思いつつサボってたら経緯どんどん忘れて来たのでここに書きなぐっておく
