### ISSUE TITLE
`.github/dependabot.yml` って案外色々設定できるんだな・・・という話

### ISSUE THREAD

**Issue by kachick** [kachick/times_kachick#85]
```yaml
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
```

え、要は書くことなんてこれだけで、変わるのは package-ecosystem が npm か bundler かみたいなのと、interval が daily か weekly かでしょ？

ぐらいの認識をしていたのだが甘かった。色々出来た。

https://github.com/kachick/ruby-ulid/commit/c99ff5089985e7be342481765328b9e7e15b08a2 が自分の学んだほぼ全てなのだが

https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#rebase-strategy
https://docs.github.com/ja/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#directory

に書いてあるように、まぁ一杯設定できるわけである。
自分が取捨選択した結果はこんな感じ

```yaml
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: increase
  - package-ecosystem: "bundler"
    directory: "/benchmark/compare_with_othergems/kachick"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: increase
  - package-ecosystem: "bundler"
    directory: "/benchmark/compare_with_othergems/rafaelsales"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: increase
  - package-ecosystem: "bundler"
    directory: "/benchmark/compare_with_othergems/abachman"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: increase
```

まず断っておくと、自分の理解が合ってるかがそもそも謎である。なのでしばらくこれで運用してみて、出されるPR眺めてみないとなんとも言えないのだが・・・・

とりあえず `package-ecosystem: "github-actions"` がまず驚きだ。はぁ、 GitHub Actions 自体の update もしてくれるんですか。凄いですね。
が、まぁ、多分滅多に update かからんだろ・・・？と思っている。なので daily は過剰な気もするけど、まぁ public リポジトリで無料で使わせていただけるわけだし、いっかなって。
このときに注意が必要なのが `directory: "/"` で、これは変に .github だの .github/workflows だのを指してはダメらしい。 github-actions ときだけ例外らしいので、ちょっと罠感はある。

ということは、逆に言うと他のは directory 指定が効くわけだ。↑のリポジトリは 他の gem との比較用 benchmark directory を切っていてそこに Gemfile を置いているのだが、こいつらも dependabot の対象に出来るんだ、へー。という感じだった。(まぁよく考えたら monorepo に対応してるんだから当たり前か monorepo とは・・・ https://github.com/joelparkerhenderson/monorepo-vs-polyrepo だ！ 対義語の polyrepo は知名度低い気がする。まぁ、はっきり言ってよく知らない。)

interval だけじゃなくて  time と timezone まで指定できるところも知らなかった。勿論 timezone 指定しなければUTCである。

versioning-strategy が、これまた知らなかったなーという感じで、詳しくは↑の公式ドキュメント読んでもらうしか無いけど、要は「上げ方」を指定できるという認識。
自分の場合は「常に最新だけ使う」感じに上がって欲しいなぁと思ったので increase を選んでみたが、これで合ってるのか全く自信がない。

まぁ、要は色々出来るんだなぁ。という話である。
尚、YAML書く時の validation については自分は vscode + https://github.com/redhat-developer/vscode-yaml を使っているのだが、こいつ単体の機能じゃないと思うんだけどやたら賢くて GitHub Actions とか dependabot の config とかを JSON schema & LSP 経由なのか？知らんが、validation してくれてとても助かる。そのうち https://github.com/kachick/times_kachick/issues/12 にまとめたい。

で、実際うまく行ったっぽいかどうかはともかく動いてそうかどうかレベルで行くと 

https://github.com/kachick/ruby-ulid/network/updates

で確認できる認識をしている。https://github.com/kachick/times_kachick/issues/73 みたいなパースエラー発生してたらアラート表示されるし、動いていれば

<img width="871" alt="スクリーンショット 2021-05-27 4 13 54" src="https://user-images.githubusercontent.com/1180335/119717977-f8e98e00-bea1-11eb-829e-7415305afef0.png">

こんな感じである
